name: AWS Sustainability Scanner GitHub Action
author: AWS Sustainability
description: Run AWS Sustainability Scanner against infrastructure as code as a pre-packaged GitHub Action
branding:
  icon: check-circle
  color: green
inputs:
  file:
    description: File path of the CloudFormation template to be scanned
    required: false
  directory:
    description: Directory path with CloudFormation files to be scanned
    required: false
    default: '.'
  stack_name:
    description: CDK stack name to be scanned
    required: false
  rules_file:
    description: File path to extend set of rules
    required: false
outputs:
  results:
    description: Results from the sustainability scan
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.file }}
    - ${{ inputs.directory }}
    - ${{ inputs.stack_name }}
    - ${{ inputs.rules_file }}