# action.yml
name: 'AWS Sustainability Scanner GitHub Action'
author: 'AWS Sustainability'
description: 'Run AWS Sustainability Scanner against infrastructure as code as a pre-packaged GitHub Action.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  file:
    description: 'File path of template to scan'
    required: false
  directory:
    description: 'Directory path with template files to scan'
    required: false
    default: '.'
  rules_file:
    description: 'File path to extend set of rules'
    required: false
outputs:
  results:
    description: 'The results from the sustainability scan'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.directory }}
    - ${{ inputs.rules_file }}